{
 "title": "My Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "My Counter",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 0 },
   "targets": [
    { "expr": "my_counter" }
   ]
  },
  {
   "title": "My Logs",
   "type": "logs",
   "gridPos": { "h": 28, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/logs/collector.log\",job=\"logging\"}"
    }
   ]
  },
  {
   "title": "My Gauge",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 14 },
   "targets": [
    { "expr": "my_gauge" }
   ]
  }
 ]
}